import { ContextProvider } from "@/context";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import DashboardWrapper from "./dashboardWrapper";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <DashboardWrapper>{children}</DashboardWrapper>
        </ContextProvider>
      </body>
    </html>
  );
}
